#!/bin/bash
#Christopher Budiharto
#Purpose: This script restores files from existing backups
#Last Revision Date: 12/08/2023 

PARAM1=$1 #Positional argument taken as a path to backup archive

errmsg(){ #errmsg() function displays help message if positional parameter is either missing or erroneous
  echo "'USAGE:./restore /path/to/backup/file'" #Error message being printed to stdout
}

warn(){ #warn() function displays warning if file/directory is about to be overwritten
  echo "You are about to overwrite an existing file/directory" #Warning message printed out
  read -p "Are you sure you want to proceed (y/n): " OPTION #Reading input to ask user if they want to proceed with the override

  if [[ $OPTION == 'y' || $OPTION == 'Y' ]] #Checks for both lower and uppercase input
  then
    return; #Returns control to the calling function
  elif [[ $OPTION == 'n' || $OPTION == 'N' ]] #Checks for both lower and uppercase input
  then
    echo $'\n'
    echo "No files overwritten." #Prints this if user does not want to overwrite files 
    exit 1 #Exits program with error code 1
  fi

}

if [[ -e $PARAM1 && $(basename "$PARAM1") == $(hostname).*.tar.gz ]] #Checks to see if the backup file exists and that it matches the backup string format
then
  if [[ ! -d /backup/restore ]] #Checks if the restore subdirectory did not exist
  then
    mkdir /backup/restore #Creates subdirectory if subdirectory did not exist
  fi

  cp $PARAM1 /backup/restore #Copies the backup archive over to the restore subdirectory
  mv /backup/restore/$(basename "$PARAM1") /backup/restore/restore.tar.gz #Renames it to restore.tar.gz to make it easier for tar to extract

  warn #Calls warn() to ask user for input

  if tar --overwrite --exclude=aquota.user -xzf /backup/restore/restore.tar.gz -C / #Extracts tar archive to target directory 
  then
    echo $'\n'
    echo "Restore complete!" #Gets printed if overwrite is successful
  fi



  rm -rf /backup/restore #Clean up to remove restore subdirectory from within /backup
else
  errmsg #errmsg() call if positional parameter was not included or wrong
fi

#successful escape code
exit 0

